version: '3.7'
services:
  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=aerotransit_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
