import Config

# Configure your database
config :aerotransit, Aerotransit.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "aerotransit_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application.
config :aerotransit, AerotransitWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "2IonXHutdS6iP1TOXNe8P7LgdJQhn4IldyOSi0IErvVEGTVC6++sMk/ksewuVkn7",
  watchers: [
    # Start the vite watcher
    node: [
      "node_modules/.bin/vite",
      cd: Path.expand("..", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :aerotransit, AerotransitWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/aerotransit_web/schema/.*(ex)$",
      ~r"lib/aerotransit_web/(live|views)/.*(ex)$",
      ~r"lib/aerotransit_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :joken,
  default_signer: [
    signer_alg: "RS256",
    key_pem: """
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKAIBAAKCAgEAq1uW1HZxCo+vZz3O97IFL9fQe32ZwC5wCEGpkP4Jy/eQV2EykIqextw3KLyITV3lKw3XuluvZ0GNhll5SrIOjhBtcLKEjORHNcKEswYX8mukAtFU2wBRM8vPCRpjPDbatAW42N+tmCTEd4XWIOfis1HO6QUQRT50Pi0t7ZSaFcWNrMfdheBhqhxAImm0Z51AQ7fL0HNjC1vyMNSEkG7La3c7MxrwLGv370MtC4yENb/qKHDZg60HP2Y2qbqFrwHYndA7VNp0R0Hi5cCLo8Yp++Uq/IXrCV7QJrxp9nGjFHhaWHE5qzh/txBtoE/e8HabE6fGIcvV3Ow3LpD4gdQ3ML0yGROQZyt6IumEMTMtCzECeKpT8InYY81Kafp5hUQcItRDSi4pJzaLTa18TveFz8iEr7kakZdWBtf0VLEfAdg0Cu/KxthEj518JXVCfohr/cZruM9d2tJLJX8uAsEgQeac4yx8Jhrq9bOvG5xT/PWhxaM7kT/ah6yRsp/kvl+/RdpEgnG0QvmVSWmixC1s9w4bIrkZs+sd+l3qaERTYnFBM+bieDhVfjUSQmE7XR43Xlgn8ij6pEIMobWyaPvfT320vuP6+c2OgOkpR9k1OqNOmsalWsNAzLYxLtwo2hpnhKqzvY11c35xqSuwUtSYnxzpsfHxhwK41y4I+RNTqkECAwEAAQKCAgB+5zJ5oEmxL54QEHcxe1ZaCzMr8WWnLPztMGu6pFhvBKWSALqozvAth7MV6SHsYggw7WyBaBsrliGQiLzJ87nRvhq+poaBrSGLj8YkqvObJdpt98cm9UIt4Ncv/6nUUy9+uOofOu/dyAT0G1rsPa7nbEOW0JgvH8SIs37a/v1p+Ecm2VGWLwlFKOzaT3w6a/vG6tv3QSztoadoQEr4iAUATmm6PE34J/GS8SXv8p2LDNkGICUGXmMKsdDzu937MJvSq/70pWAN0Z6O1hzUKhK3qQ0/vJHG+7+doFW9HIVQyJzn+NpjklELKxB09BG/9aZ9VPfn2YRFu25Wfyh7RcWkjRYWcBWAeJW6Dlq327i7Ym9zVw/B2s+Ge8JjpxTI1YZWDJs25qIy98sbYoVNyO13GAdXpH76fwT1KEURVHbwRgA7UD7v9G2W1NYSqOC/epKPR/6iNq81XgdHczUQ3RCJhZhMhV0VXtCjKxO/bS2w9S9c29Q8AjOOWQEjX8lam2pV7yCMA3K/A9XwLjjZZv3fmky/STYM/qpD9bKHR3kw8GDnBJIY+960tBb2daUjOpz2zr+MiSPveZDX8GV50Ne+Dj2lfmArRMH26PjbxyP4eIxEnPiB01TOTVWriOdDjTRfqp99d4UVOMZidNYUzVryTb/Cwg1IJN+X+XZD2JufnQKCAQEA3VjARriOqq2t4ndFZrYVfoITa227CjCSjCrsEWU0rw6Vjk1rdwjf9aS9KEc/8IN0r1Kl1/xxVGvMVWbXVA27FYgLXTJ3VSAScekNVvVqMpR6166QXmoMjAPzMZGDkGzlhz7OKiMb/qv5NnOy1c1LzOAaiC3IpUHR4SrN3k4QBG2fUZU0HkTtruIEgAqCdozHtTFoKIFyXH54IHurq+8wxc3zQuLSgwyNqC0eHnL58u/36w1ksJ7h5jzweJRYGDctsjpk6sCppg61V8UNmGNt1OUC7zdg109epXbGthe6p7MSmibUvFQ7sE+gcafZQt9MDNTYgbjBRf5eQGIHlIjxdwKCAQEAxi9bKYnOT+8qYGGftgjCFcDmKdULyjLbrOYAndCINLkZHL/AH7Ao0cax3jN1epl6CUpYbcE9yHQWoESul+SfnaBG0ZO0caudukyKDy/3o94zShAT9rke8+Q/sVLn8SabRVFGXWeDpZxnYRvP5gO5cN5PFcCfh1odPcBhJsWIZEqPSALVOO/Vnk6sSZSsB2aWdre1CY3ZK4zJPaVwaj9H1JJGeMXrdXmhl24brQ0Wx3Zg1NdxbqwAvO9hDyMWEo4Y7wZQGXezO1HYWTasMaQGOOV3Bv6rKxTRnG9l8jl1zOkXapYIr4crx63Rn1NDuXFMDfdMd3P1AGhPxVEA6ddwBwKCAQBROU0tZnIr3ZnOXbgg7bZLew4HQPf+0D4mo2WHKJ1Bk9d7pZtGzgHpES+8hRDIgGSkJW7oKCGqOfh8akWf+X3qc8a/x1IU8bTzCfM0MtBqiSPe25bsnnvGMXjfeqdNqzg6/egHfGS8enzz51b7r98d6iqySCK1ycZrmxp6dijYhyWMeXTrmp2hrBy8o56mRBjQu7WeD4pYuKv6N4eSiy5Zl66pn7RiFIwy54OC5uwjor1WCs8lJNh+dWREyyLcl/rzyQvZPSPD5OfUsmG/xtS55+PAxpCJ0f1IOKLIlUKQYVz1JkSwazSQCVg1/ML0EB7HIp/kUljSB3qso4xmjC4XAoIBABlEyHbPX0LJ17laOSbYjwZ/BdmnlE0/lsrAuKtmfzdZsl38BN8Fcu7sSpluLjhngSvWEthLnzkDtC7TEv/C4qcSXHU0Q/mKTB4IzEGLeCOonRmAW0tF5zBplcViMLiKl5mK91HJdPuUqYm0JhnJt8cwUR0Q5kY3syrAcKKk5PMEnqgr1EviKHZ6yXTIQ/bdmamhWq/RKjNnS/FUOrURRHNSAzI66f6cd4H7RAQYeyMLcOUyYwAdZiqwystHSfUrsPoo7+WPYYbatJ8LXYEmzLRMbZSyu9hOWzt66KCtuttZjObGIm1e6rIW83dBAo2OaIgPU+yXGFHo+uLJpTgrg9kCggEBAKESca7AFQgF8uXv3VLZzGXjDX4hbHPVioA3DBeSN/DHovDl2Mx50iLzmisUF9/OQPaJuEer/mhpO7ANzcR2eyPtI08boS1IUu6dYhBqDUXrLRsUzjJNLNQy4ePB1uyQXl0eXc6IEQy+0WDAIahX/I5gbsRAMhXykZ+HlYarpRPwhixwXfr0v7yXsJ/IcM7Dd5iCk6QxDCjvh0zfTIRwJATf9pUHJHkTPaJKp6Nq36AX1vvhMQ2Dw3U8yq7AAh0yVZNRLZSCLXgFOmxCub1sGTttsCzeF+Teyhz8WcmBZR+EplkDftDUvcWkkWfYvsvN6FhyWZ0k2LXDympPmENMVAY=
    -----END RSA PRIVATE KEY-----
    """
  ]
